// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using WebPlex.MvcApplication;
namespace WebPlex.MvcApplication
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Content_Alerts = "_Content_Alerts";
                public readonly string _Content_Breadcrumb = "_Content_Breadcrumb";
                public readonly string _Content_Navbar = "_Content_Navbar";
                public readonly string _DefaultLayout = "_DefaultLayout";
                public readonly string _EmptyLayout = "_EmptyLayout";
                public readonly string _Footer = "_Footer";
                public readonly string _LayoutBase = "_LayoutBase";
                public readonly string _Scripts = "_Scripts";
                public readonly string _Styles = "_Styles";
            }
            public readonly string _Content_Alerts = "~/Views/Shared/_Content_Alerts.cshtml";
            public readonly string _Content_Breadcrumb = "~/Views/Shared/_Content_Breadcrumb.cshtml";
            public readonly string _Content_Navbar = "~/Views/Shared/_Content_Navbar.cshtml";
            public readonly string _DefaultLayout = "~/Views/Shared/_DefaultLayout.cshtml";
            public readonly string _EmptyLayout = "~/Views/Shared/_EmptyLayout.cshtml";
            public readonly string _Footer = "~/Views/Shared/_Footer.cshtml";
            public readonly string _LayoutBase = "~/Views/Shared/_LayoutBase.cshtml";
            public readonly string _Scripts = "~/Views/Shared/_Scripts.cshtml";
            public readonly string _Styles = "~/Views/Shared/_Styles.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Boolean = "Boolean";
                public readonly string EmailAddress = "EmailAddress";
                public readonly string Password = "Password";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
