//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPlex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPlex.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string Boolean_False {
            get {
                return ResourceManager.GetString("Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعلوم.
        /// </summary>
        public static string Boolean_NotSpecified {
            get {
                return ResourceManager.GetString("Boolean_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Boolean_True {
            get {
                return ResourceManager.GetString("Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, dd MMMM yyyy.
        /// </summary>
        public static string Georgian_Format {
            get {
                return ResourceManager.GetString("Georgian_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Numeric_NotSpecified {
            get {
                return ResourceManager.GetString("Numeric_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00 Bytes.
        /// </summary>
        public static string PrettySize_Bytes {
            get {
                return ResourceManager.GetString("PrettySize_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00 GB.
        /// </summary>
        public static string PrettySize_Gigabyte {
            get {
                return ResourceManager.GetString("PrettySize_Gigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00 KB.
        /// </summary>
        public static string PrettySize_Kilobyte {
            get {
                return ResourceManager.GetString("PrettySize_Kilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00 MB.
        /// </summary>
        public static string PrettySize_Megabyte {
            get {
                return ResourceManager.GetString("PrettySize_Megabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00 TB.
        /// </summary>
        public static string PrettySize_Terabyte {
            get {
                return ResourceManager.GetString("PrettySize_Terabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یه دقیقه پیش.
        /// </summary>
        public static string PrettyTime_AMinAgo {
            get {
                return ResourceManager.GetString("PrettyTime_AMinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه گذشته.
        /// </summary>
        public static string PrettyTime_LastMonth {
            get {
                return ResourceManager.GetString("PrettyTime_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفته گذشته.
        /// </summary>
        public static string PrettyTime_LastWeek {
            get {
                return ResourceManager.GetString("PrettyTime_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال گذشته.
        /// </summary>
        public static string PrettyTime_LastYear {
            get {
                return ResourceManager.GetString("PrettyTime_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} روز قبل.
        /// </summary>
        public static string PrettyTime_NDaysAgo {
            get {
                return ResourceManager.GetString("PrettyTime_NDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ساعت پیش.
        /// </summary>
        public static string PrettyTime_NHourAgo {
            get {
                return ResourceManager.GetString("PrettyTime_NHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} دقیقه پیش.
        /// </summary>
        public static string PrettyTime_NMinAgo {
            get {
                return ResourceManager.GetString("PrettyTime_NMinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ماه پیش.
        /// </summary>
        public static string PrettyTime_NMonthAgo {
            get {
                return ResourceManager.GetString("PrettyTime_NMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همین الان.
        /// </summary>
        public static string PrettyTime_Now {
            get {
                return ResourceManager.GetString("PrettyTime_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ثانیه پیش.
        /// </summary>
        public static string PrettyTime_NSecAgo {
            get {
                return ResourceManager.GetString("PrettyTime_NSecAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} سال قبل.
        /// </summary>
        public static string PrettyTime_NYearAgo {
            get {
                return ResourceManager.GetString("PrettyTime_NYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه هفته پیش.
        /// </summary>
        public static string PrettyTime_ThreeWeekAgo {
            get {
                return ResourceManager.GetString("PrettyTime_ThreeWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو هفته پیش.
        /// </summary>
        public static string PrettyTime_TwoWeekAgo {
            get {
                return ResourceManager.GetString("PrettyTime_TwoWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیروز.
        /// </summary>
        public static string PrettyTime_Yesterday {
            get {
                return ResourceManager.GetString("PrettyTime_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعلوم.
        /// </summary>
        public static string String_NotSpecified {
            get {
                return ResourceManager.GetString("String_NotSpecified", resourceCulture);
            }
        }
    }
}
