//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPlex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Members {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Members() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPlex.Resources.Members", typeof(Members).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بذار کاربرامون بتونن زبان رو تغییر بدن..
        /// </summary>
        public static string ApplicationSettings_AllowUsersToSetLanguage {
            get {
                return ResourceManager.GetString("ApplicationSettings_AllowUsersToSetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بذار کاربرامون بتونن ناحیه زمانی رو تغییر بدن..
        /// </summary>
        public static string ApplicationSettings_AllowUsersToSetTimeZone {
            get {
                return ResourceManager.GetString("ApplicationSettings_AllowUsersToSetTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان پیشفرض.
        /// </summary>
        public static string ApplicationSettings_DefaultLanguage {
            get {
                return ResourceManager.GetString("ApplicationSettings_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناحیه زمانی پیشفرض.
        /// </summary>
        public static string ApplicationSettings_DefaultTimeZoneId {
            get {
                return ResourceManager.GetString("ApplicationSettings_DefaultTimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید رمزنگاری.
        /// </summary>
        public static string ApplicationSettings_EncryptionKey {
            get {
                return ResourceManager.GetString("ApplicationSettings_EncryptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جداکننده عنوان صفحات.
        /// </summary>
        public static string ApplicationSettings_TitleSeparator {
            get {
                return ResourceManager.GetString("ApplicationSettings_TitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید.
        /// </summary>
        public static string AttributeEntityBase_Key {
            get {
                return ResourceManager.GetString("AttributeEntityBase_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string AttributeEntityBase_Value {
            get {
                return ResourceManager.GetString("AttributeEntityBase_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضا.
        /// </summary>
        public static string BannedIpEntity_ExpireDateUtc {
            get {
                return ResourceManager.GetString("BannedIpEntity_ExpireDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس آی‌پی.
        /// </summary>
        public static string BannedIpEntity_IpAdrress {
            get {
                return ResourceManager.GetString("BannedIpEntity_IpAdrress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلیل....
        /// </summary>
        public static string BannedIpEntity_Reason {
            get {
                return ResourceManager.GetString("BannedIpEntity_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string BannedIpEntity_StartDateUtc {
            get {
                return ResourceManager.GetString("BannedIpEntity_StartDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شب فعلی.
        /// </summary>
        public static string ChangePasswordModel_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شب جدید.
        /// </summary>
        public static string ChangePasswordModel_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شب جدید (دوباره).
        /// </summary>
        public static string ChangePasswordModel_NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("ChangePasswordModel_NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم پوشه.
        /// </summary>
        public static string CloudSettings_BackupFolder {
            get {
                return ResourceManager.GetString("CloudSettings_BackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید اختصاصی.
        /// </summary>
        public static string CloudSettings_ConsumerKey {
            get {
                return ResourceManager.GetString("CloudSettings_ConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مخفی اختصاصی.
        /// </summary>
        public static string CloudSettings_ConsumerSecret {
            get {
                return ResourceManager.GetString("CloudSettings_ConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string CloudSettings_Password {
            get {
                return ResourceManager.GetString("CloudSettings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string CloudSettings_UserName {
            get {
                return ResourceManager.GetString("CloudSettings_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دریافت کننده.
        /// </summary>
        public static string ContactFormSettings_RecipientName {
            get {
                return ResourceManager.GetString("ContactFormSettings_RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string ContactFormSettings_Subject {
            get {
                return ResourceManager.GetString("ContactFormSettings_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه.
        /// </summary>
        public static string ContactModel_Email {
            get {
                return ResourceManager.GetString("ContactModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیغام....
        /// </summary>
        public static string ContactModel_Message {
            get {
                return ResourceManager.GetString("ContactModel_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسمتون.
        /// </summary>
        public static string ContactModel_Name {
            get {
                return ResourceManager.GetString("ContactModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه.
        /// </summary>
        public static string EmailAccountEntity_Email {
            get {
                return ResourceManager.GetString("EmailAccountEntity_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس میزبان.
        /// </summary>
        public static string EmailAccountEntity_Host {
            get {
                return ResourceManager.GetString("EmailAccountEntity_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید داخلی.
        /// </summary>
        public static string EmailAccountEntity_InternalKey {
            get {
                return ResourceManager.GetString("EmailAccountEntity_InternalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به عنوان حساب پیشفرض در نظر بگیر..
        /// </summary>
        public static string EmailAccountEntity_IsDefault {
            get {
                return ResourceManager.GetString("EmailAccountEntity_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string EmailAccountEntity_Name {
            get {
                return ResourceManager.GetString("EmailAccountEntity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string EmailAccountEntity_Password {
            get {
                return ResourceManager.GetString("EmailAccountEntity_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پورت.
        /// </summary>
        public static string EmailAccountEntity_Port {
            get {
                return ResourceManager.GetString("EmailAccountEntity_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL فعال باشه..
        /// </summary>
        public static string EmailAccountEntity_SslEnabled {
            get {
                return ResourceManager.GetString("EmailAccountEntity_SslEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از نام کاربری و گذرواژه پیشفرض استفاده کن..
        /// </summary>
        public static string EmailAccountEntity_UseDefaultCredentials {
            get {
                return ResourceManager.GetString("EmailAccountEntity_UseDefaultCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string EmailAccountEntity_UserName {
            get {
                return ResourceManager.GetString("EmailAccountEntity_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب نمایش.
        /// </summary>
        public static string EntityBase_DisplayOrder {
            get {
                return ResourceManager.GetString("EntityBase_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string EntityBase_Id {
            get {
                return ResourceManager.GetString("EntityBase_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت فعال.
        /// </summary>
        public static string EntityBase_IsEnabled {
            get {
                return ResourceManager.GetString("EntityBase_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string EntityBase_Version {
            get {
                return ResourceManager.GetString("EntityBase_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیغام کامل.
        /// </summary>
        public static string LogEntity_FullMessage {
            get {
                return ResourceManager.GetString("LogEntity_FullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باعث و بانیش.
        /// </summary>
        public static string LogEntity_Invoker {
            get {
                return ResourceManager.GetString("LogEntity_Invoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس آی‌پی (بانی).
        /// </summary>
        public static string LogEntity_InvokerIp {
            get {
                return ResourceManager.GetString("LogEntity_InvokerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string LogEntity_LogDateUtc {
            get {
                return ResourceManager.GetString("LogEntity_LogDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس رفرر.
        /// </summary>
        public static string LogEntity_ReferrerUrl {
            get {
                return ResourceManager.GetString("LogEntity_ReferrerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس درخواست.
        /// </summary>
        public static string LogEntity_RequestUrl {
            get {
                return ResourceManager.GetString("LogEntity_RequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شدت (نوع).
        /// </summary>
        public static string LogEntity_Severity {
            get {
                return ResourceManager.GetString("LogEntity_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استک-تریس.
        /// </summary>
        public static string LogEntity_StackTrace {
            get {
                return ResourceManager.GetString("LogEntity_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایابی.
        /// </summary>
        public static string LogSeverity_Debug {
            get {
                return ResourceManager.GetString("LogSeverity_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string LogSeverity_Error {
            get {
                return ResourceManager.GetString("LogSeverity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحرانی.
        /// </summary>
        public static string LogSeverity_Fatal {
            get {
                return ResourceManager.GetString("LogSeverity_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات.
        /// </summary>
        public static string LogSeverity_Information {
            get {
                return ResourceManager.GetString("LogSeverity_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        public static string LogSeverity_Warning {
            get {
                return ResourceManager.GetString("LogSeverity_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کامنت.
        /// </summary>
        public static string MembershipEntity_AdminComment {
            get {
                return ResourceManager.GetString("MembershipEntity_AdminComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه تائید.
        /// </summary>
        public static string MembershipEntity_ConfirmationToken {
            get {
                return ResourceManager.GetString("MembershipEntity_ConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string MembershipEntity_CreateDateUtc {
            get {
                return ResourceManager.GetString("MembershipEntity_CreateDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تائید.
        /// </summary>
        public static string MembershipEntity_IsConfirmed {
            get {
                return ResourceManager.GetString("MembershipEntity_IsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت مسدود.
        /// </summary>
        public static string MembershipEntity_IsLocked {
            get {
                return ResourceManager.GetString("MembershipEntity_IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین فعالیت.
        /// </summary>
        public static string MembershipEntity_LastActivityDateUtc {
            get {
                return ResourceManager.GetString("MembershipEntity_LastActivityDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین آدرس آی‌پی.
        /// </summary>
        public static string MembershipEntity_LastIpAddress {
            get {
                return ResourceManager.GetString("MembershipEntity_LastIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین قفل شدن.
        /// </summary>
        public static string MembershipEntity_LastLockoutDateUtc {
            get {
                return ResourceManager.GetString("MembershipEntity_LastLockoutDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین ورود.
        /// </summary>
        public static string MembershipEntity_LastLoginDateUtc {
            get {
                return ResourceManager.GetString("MembershipEntity_LastLoginDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین تغییر گذرواژه.
        /// </summary>
        public static string MembershipEntity_LastPasswordChangeDateUtc {
            get {
                return ResourceManager.GetString("MembershipEntity_LastPasswordChangeDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین گذرواژه اشتباه.
        /// </summary>
        public static string MembershipEntity_LastPasswordFailureDateUtc {
            get {
                return ResourceManager.GetString("MembershipEntity_LastPasswordFailureDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string MembershipEntity_Password {
            get {
                return ResourceManager.GetString("MembershipEntity_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تلاش‌های ناموفق.
        /// </summary>
        public static string MembershipEntity_PasswordFailuresSinceLastSuccess {
            get {
                return ResourceManager.GetString("MembershipEntity_PasswordFailuresSinceLastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه تغییر گذرواژه.
        /// </summary>
        public static string MembershipEntity_PasswordVerificationToken {
            get {
                return ResourceManager.GetString("MembershipEntity_PasswordVerificationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضای شناسه تغییر گذرواژه.
        /// </summary>
        public static string MembershipEntity_PasswordVerificationTokenExpirationDateUtc {
            get {
                return ResourceManager.GetString("MembershipEntity_PasswordVerificationTokenExpirationDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string MembershipEntity_User {
            get {
                return ResourceManager.GetString("MembershipEntity_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه فراهم‌کننده.
        /// </summary>
        public static string OAuthEntity_ProviderKey {
            get {
                return ResourceManager.GetString("OAuthEntity_ProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string OAuthEntity_User {
            get {
                return ResourceManager.GetString("OAuthEntity_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر.
        /// </summary>
        public static string OAuthEntity_UserKey {
            get {
                return ResourceManager.GetString("OAuthEntity_UserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید مخفی.
        /// </summary>
        public static string OAuthTokenEntity_Secret {
            get {
                return ResourceManager.GetString("OAuthTokenEntity_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string OAuthTokenEntity_Token {
            get {
                return ResourceManager.GetString("OAuthTokenEntity_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معمولی.
        /// </summary>
        public static string PasswordPersistenceMode_Clear {
            get {
                return ResourceManager.GetString("PasswordPersistenceMode_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزنگاری شده.
        /// </summary>
        public static string PasswordPersistenceMode_Encrypted {
            get {
                return ResourceManager.GetString("PasswordPersistenceMode_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزنگاری یک طرفه (پیشنهاد شده).
        /// </summary>
        public static string PasswordPersistenceMode_Hashed {
            get {
                return ResourceManager.GetString("PasswordPersistenceMode_Hashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه.
        /// </summary>
        public static string PermissionEntity_Group {
            get {
                return ResourceManager.GetString("PermissionEntity_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید داخلی.
        /// </summary>
        public static string PermissionEntity_InternalKey {
            get {
                return ResourceManager.GetString("PermissionEntity_InternalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string PermissionEntity_Name {
            get {
                return ResourceManager.GetString("PermissionEntity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش‌ها.
        /// </summary>
        public static string PermissionEntity_Roles {
            get {
                return ResourceManager.GetString("PermissionEntity_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید داخلی.
        /// </summary>
        public static string PermissionGroupEntity_InternalKey {
            get {
                return ResourceManager.GetString("PermissionGroupEntity_InternalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string PermissionGroupEntity_Name {
            get {
                return ResourceManager.GetString("PermissionGroupEntity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی‌ها.
        /// </summary>
        public static string PermissionGroupEntity_Permissions {
            get {
                return ResourceManager.GetString("PermissionGroupEntity_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش‌ها.
        /// </summary>
        public static string PermissionGroupEntity_Roles {
            get {
                return ResourceManager.GetString("PermissionGroupEntity_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بی-سی-سی.
        /// </summary>
        public static string QueuedMailEntity_Bcc {
            get {
                return ResourceManager.GetString("QueuedMailEntity_Bcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن رایانامه.
        /// </summary>
        public static string QueuedMailEntity_Body {
            get {
                return ResourceManager.GetString("QueuedMailEntity_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سی-سی.
        /// </summary>
        public static string QueuedMailEntity_Cc {
            get {
                return ResourceManager.GetString("QueuedMailEntity_Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه فرستنده.
        /// </summary>
        public static string QueuedMailEntity_FromEmail {
            get {
                return ResourceManager.GetString("QueuedMailEntity_FromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرستنده.
        /// </summary>
        public static string QueuedMailEntity_FromName {
            get {
                return ResourceManager.GetString("QueuedMailEntity_FromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهمیت.
        /// </summary>
        public static string QueuedMailEntity_Importance {
            get {
                return ResourceManager.GetString("QueuedMailEntity_Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به عنوان متن HTML در نظر بگیر..
        /// </summary>
        public static string QueuedMailEntity_IsBodyHtml {
            get {
                return ResourceManager.GetString("QueuedMailEntity_IsBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفعات تلاش برای ارسال.
        /// </summary>
        public static string QueuedMailEntity_SendTries {
            get {
                return ResourceManager.GetString("QueuedMailEntity_SendTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ارسال.
        /// </summary>
        public static string QueuedMailEntity_SentDateUtc {
            get {
                return ResourceManager.GetString("QueuedMailEntity_SentDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string QueuedMailEntity_Subject {
            get {
                return ResourceManager.GetString("QueuedMailEntity_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه گیرنده.
        /// </summary>
        public static string QueuedMailEntity_ToEmail {
            get {
                return ResourceManager.GetString("QueuedMailEntity_ToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گیرنده.
        /// </summary>
        public static string QueuedMailEntity_ToName {
            get {
                return ResourceManager.GetString("QueuedMailEntity_ToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحرانی.
        /// </summary>
        public static string QueuedMailImportance_Critical {
            get {
                return ResourceManager.GetString("QueuedMailImportance_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیاد.
        /// </summary>
        public static string QueuedMailImportance_High {
            get {
                return ResourceManager.GetString("QueuedMailImportance_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کم.
        /// </summary>
        public static string QueuedMailImportance_Low {
            get {
                return ResourceManager.GetString("QueuedMailImportance_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معمولی.
        /// </summary>
        public static string QueuedMailImportance_Normal {
            get {
                return ResourceManager.GetString("QueuedMailImportance_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه.
        /// </summary>
        public static string ResetPasswordModel_Email {
            get {
                return ResourceManager.GetString("ResetPasswordModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه‌ها.
        /// </summary>
        public static string RoleEntity_Groups {
            get {
                return ResourceManager.GetString("RoleEntity_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید داخلی.
        /// </summary>
        public static string RoleEntity_InternalKey {
            get {
                return ResourceManager.GetString("RoleEntity_InternalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string RoleEntity_Name {
            get {
                return ResourceManager.GetString("RoleEntity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی‌ها.
        /// </summary>
        public static string RoleEntity_Permissions {
            get {
                return ResourceManager.GetString("RoleEntity_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string RoleEntity_Users {
            get {
                return ResourceManager.GetString("RoleEntity_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیاد.
        /// </summary>
        public static string ScheduleTaskImportance_High {
            get {
                return ResourceManager.GetString("ScheduleTaskImportance_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کم.
        /// </summary>
        public static string ScheduleTaskImportance_Low {
            get {
                return ResourceManager.GetString("ScheduleTaskImportance_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معمولی.
        /// </summary>
        public static string ScheduleTaskImportance_Normal {
            get {
                return ResourceManager.GetString("ScheduleTaskImportance_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید.
        /// </summary>
        public static string SettingEntity_Key {
            get {
                return ResourceManager.GetString("SettingEntity_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string SettingEntity_Value {
            get {
                return ResourceManager.GetString("SettingEntity_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه.
        /// </summary>
        public static string SignInModel_Email {
            get {
                return ResourceManager.GetString("SignInModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شب.
        /// </summary>
        public static string SignInModel_Password {
            get {
                return ResourceManager.GetString("SignInModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیگه ازم نپرس!.
        /// </summary>
        public static string SignInModel_RememberMe {
            get {
                return ResourceManager.GetString("SignInModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه.
        /// </summary>
        public static string SignUpModel_Email {
            get {
                return ResourceManager.GetString("SignUpModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شب.
        /// </summary>
        public static string SignUpModel_Password {
            get {
                return ResourceManager.GetString("SignUpModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شب (دوباره).
        /// </summary>
        public static string SignUpModel_PasswordConfirmation {
            get {
                return ResourceManager.GetString("SignUpModel_PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انصراف.
        /// </summary>
        public static string SubscriptionEntity_CancelDateUtc {
            get {
                return ResourceManager.GetString("SubscriptionEntity_CancelDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تائید.
        /// </summary>
        public static string SubscriptionEntity_ConfirmDateUtc {
            get {
                return ResourceManager.GetString("SubscriptionEntity_ConfirmDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه.
        /// </summary>
        public static string SubscriptionEntity_Email {
            get {
                return ResourceManager.GetString("SubscriptionEntity_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string SubscriptionEntity_Status {
            get {
                return ResourceManager.GetString("SubscriptionEntity_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت درخواست.
        /// </summary>
        public static string SubscriptionEntity_SubscribDateUtc {
            get {
                return ResourceManager.GetString("SubscriptionEntity_SubscribDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصرافی.
        /// </summary>
        public static string SubscriptionStatus_Cancelled {
            get {
                return ResourceManager.GetString("SubscriptionStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائیدیه ارسال شده.
        /// </summary>
        public static string SubscriptionStatus_ConfirmationSent {
            get {
                return ResourceManager.GetString("SubscriptionStatus_ConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید شده.
        /// </summary>
        public static string SubscriptionStatus_Confirmed {
            get {
                return ResourceManager.GetString("SubscriptionStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلق.
        /// </summary>
        public static string SubscriptionStatus_Pending {
            get {
                return ResourceManager.GetString("SubscriptionStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string UserAttributeEntity_User {
            get {
                return ResourceManager.GetString("UserAttributeEntity_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامه.
        /// </summary>
        public static string UserEntity_Email {
            get {
                return ResourceManager.GetString("UserEntity_Email", resourceCulture);
            }
        }
    }
}
