//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPlex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPlex.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروهی که انتخاب کردی مجاز نیست!.
        /// </summary>
        public static string Authorization_InvalidGroup {
            get {
                return ResourceManager.GetString("Authorization_InvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرمیشنی که انتخاب کردی مجاز نیست!.
        /// </summary>
        public static string Authorization_InvalidPermission {
            get {
                return ResourceManager.GetString("Authorization_InvalidPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی که انتخاب کردی مجاز نیست!.
        /// </summary>
        public static string Authorization_InvalidRole {
            get {
                return ResourceManager.GetString("Authorization_InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری که انتخاب کردی مجاز نیست!.
        /// </summary>
        public static string Authorization_InvalidUser {
            get {
                return ResourceManager.GetString("Authorization_InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توی روند اجرای درخواستت مشکلی رخ داده!.
        /// </summary>
        public static string Common_ActionFailed {
            get {
                return ResourceManager.GetString("Common_ActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواستت با موفقیت انجام شد..
        /// </summary>
        public static string Common_ActionSucceded {
            get {
                return ResourceManager.GetString("Common_ActionSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدا می خوای پاکش کنی؟ دیگه بر نمی گرده ها!.
        /// </summary>
        public static string Common_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Common_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشد که حذف شه :D آخیش!.
        /// </summary>
        public static string Common_DeleteFailed {
            get {
                return ResourceManager.GetString("Common_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شد! حالا راحت شدی؟.
        /// </summary>
        public static string Common_DeleteSucceded {
            get {
                return ResourceManager.GetString("Common_DeleteSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من با هیچی (null) چیکار کنم؛ ها؟ نه خودت بگو!.
        /// </summary>
        public static string Common_NullEntity {
            get {
                return ResourceManager.GetString("Common_NullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چیزی ذخیره نشد؛ حتما یه جای کارت میلنگه!.
        /// </summary>
        public static string Common_SaveFailed {
            get {
                return ResourceManager.GetString("Common_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره شد..
        /// </summary>
        public static string Common_SaveSucceded {
            get {
                return ResourceManager.GetString("Common_SaveSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فکر کنم یه خورده دیر جنبیدی؛ قبلا حذف شده!.
        /// </summary>
        public static string Common_UnknownEntity {
            get {
                return ResourceManager.GetString("Common_UnknownEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات اولیه انجام شد..
        /// </summary>
        public static string Configuration_DefaultSettingsSucceeded {
            get {
                return ResourceManager.GetString("Configuration_DefaultSettingsSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر پیشفرص ایجاد شد..
        /// </summary>
        public static string Configuration_DefaultUserSucceeded {
            get {
                return ResourceManager.GetString("Configuration_DefaultUserSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثل اینکه توی ارسال پیامتون مشکلی پیش اومده! پوزش مارو بپذیرین و مجددا تلاش کنید. باز هم بخاطر مشکل پیش اومده متاسفیم..
        /// </summary>
        public static string Contact_SendMessageFailed {
            get {
                return ResourceManager.GetString("Contact_SendMessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامتون رو دریافت کردیم. لطفا منتظر پاسخ ما باشین. سعی می کنیم در اسرع وقت باهاتون تماس بگیریم. مرسی :).
        /// </summary>
        public static string Contact_SendMessageSucceded {
            get {
                return ResourceManager.GetString("Contact_SendMessageSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یدونه &quot;حساب ایمیل&quot; نگه دار! خبر نامه هارو با چی باید بفرستیم؟.
        /// </summary>
        public static string EmailAccounts_AtLeastOneEmailAccountRequired {
            get {
                return ResourceManager.GetString("EmailAccounts_AtLeastOneEmailAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شیطونی نکن!.
        /// </summary>
        public static string Errors_Error403 {
            get {
                return ResourceManager.GetString("Errors_Error403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر چند به چهره‌ت نمیخوره ولی یا شیطونی کردی یا می خوای بکنی؛ نکن برادر/خواهر من نکن!.
        /// </summary>
        public static string Errors_Error403Description {
            get {
                return ResourceManager.GetString("Errors_Error403Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گشتیم نبود....
        /// </summary>
        public static string Errors_Error404 {
            get {
                return ResourceManager.GetString("Errors_Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اون چیزی که دنبالشین مثل اینکه وجود خارجی نداره؛ یا شایدم فعلا در دسترس نیست! اگر اینطور نیست لطفا باهامون تماس بگیرید..
        /// </summary>
        public static string Errors_Error404Description {
            get {
                return ResourceManager.GetString("Errors_Error404Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اوخخخ!.
        /// </summary>
        public static string Errors_Error500 {
            get {
                return ResourceManager.GetString("Errors_Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثل اینکه نرم افزار ما نمی تونه درخواستتون رو پردازش کنه :( اما نگران نباشید ما همه اون چیزی که قراره توی رفع این نقص کمک کنه رو ذخیره کردیم. حالا درخواست می کنیم که لطفا دوباره تلاش کنید..
        /// </summary>
        public static string Errors_Error500Description {
            get {
                return ResourceManager.GetString("Errors_Error500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برمیگردیم....
        /// </summary>
        public static string Errors_Error503 {
            get {
                return ResourceManager.GetString("Errors_Error503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان سرویس دهی رو نداریم. لطفا زودی برگردین ;).
        /// </summary>
        public static string Errors_Error503Description {
            get {
                return ResourceManager.GetString("Errors_Error503Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نوع سوابق ارزش ثبت شدن رو ندارن!.
        /// </summary>
        public static string Logging_LogsWithThisTypeOfSeverityIsDisabled {
            get {
                return ResourceManager.GetString("Logging_LogsWithThisTypeOfSeverityIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لزومی به ثبت استثنای ThreadAbortException وجود نداره..
        /// </summary>
        public static string Logging_ThreadAbortExceptionIsNotAllowedToBeLogged {
            get {
                return ResourceManager.GetString("Logging_ThreadAbortExceptionIsNotAllowedToBeLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب مورد نظر حذف شد..
        /// </summary>
        public static string Membership_AccountDeleteSucceded {
            get {
                return ResourceManager.GetString("Membership_AccountDeleteSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابت لاک شده؛ حتما یکی خواسته بدون اجازت وارد حساب کاربریت بشه! جان من، این تن بمیره، بیشترمراقب باش؛ گذرواژه‌ت رو هم هر چند هفته عوض کن خواهشن!.
        /// </summary>
        public static string Membership_AccountLocked {
            get {
                return ResourceManager.GetString("Membership_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابی پیدا نشد!.
        /// </summary>
        public static string Membership_AccountNotFound {
            get {
                return ResourceManager.GetString("Membership_AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابت هنوز فعال نشده! موشکل داری؟ لینک تماس با من به اون گنده‌ای؛ اوناهاش!.
        /// </summary>
        public static string Membership_ConfirmedAccountRequired {
            get {
                return ResourceManager.GetString("Membership_ConfirmedAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یه مشکلی وجود داره؛ نمی تونیم فعلا وارد شیم. دوباره تلاش کن؛ اگر بازم به مشکل خوردی حتما خبرمون کن..
        /// </summary>
        public static string Membership_ExternalSignInFailed {
            get {
                return ResourceManager.GetString("Membership_ExternalSignInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت به حسابت وارد شدی..
        /// </summary>
        public static string Membership_ExternalSignInSucceeded {
            get {
                return ResourceManager.GetString("Membership_ExternalSignInSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانامت رو درست وارد نکردی!.
        /// </summary>
        public static string Membership_InvalidEmail {
            get {
                return ResourceManager.GetString("Membership_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یا رایانامت رو درست وارد نکردی یا اسم شب رو!.
        /// </summary>
        public static string Membership_InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("Membership_InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شب قبلیت این نبود که!.
        /// </summary>
        public static string Membership_InvalidOldPassword {
            get {
                return ResourceManager.GetString("Membership_InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمی تونی قبل از اینکه یه اکانت داخلی بسازی گذرواژه‌ت رو ریست کنی یا تغییرش بدی!.
        /// </summary>
        public static string Membership_LocalAccountRequired {
            get {
                return ResourceManager.GetString("Membership_LocalAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه‌ت قبلا ثبت کردی!.
        /// </summary>
        public static string Membership_PasswordAlreadySet {
            get {
                return ResourceManager.GetString("Membership_PasswordAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه‌ت با موفقیت تغییر کرد..
        /// </summary>
        public static string Membership_PasswordChangeSucceded {
            get {
                return ResourceManager.GetString("Membership_PasswordChangeSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یه رایانامه واست می فرستیم که توش یه لینک برای تغییر گذرواژت وجود داره؛ لطفا شکیبا باش..
        /// </summary>
        public static string Membership_PasswordResetSucceded {
            get {
                return ResourceManager.GetString("Membership_PasswordResetSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه‌ت رو با موفقیت ثبت کردی..
        /// </summary>
        public static string Membership_PasswordSetSucceded {
            get {
                return ResourceManager.GetString("Membership_PasswordSetSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این حساب مربوط به تو نیست!.
        /// </summary>
        public static string Membership_RelatedProviderRequired {
            get {
                return ResourceManager.GetString("Membership_RelatedProviderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هورااا! خوش اومدی..
        /// </summary>
        public static string Membership_SignInSucceded {
            get {
                return ResourceManager.GetString("Membership_SignInSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفتی؟.
        /// </summary>
        public static string Membership_SignOutSucceded {
            get {
                return ResourceManager.GetString("Membership_SignOutSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام!!! به جمع‌مون خوش اومدی..
        /// </summary>
        public static string Membership_SignUpSucceded {
            get {
                return ResourceManager.GetString("Membership_SignUpSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش &quot;مهمان&quot; پیدا نشد!.
        /// </summary>
        public static string Roles_GuestsRoleNotFound {
            get {
                return ResourceManager.GetString("Roles_GuestsRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش &quot;ثبت‌نام شده&quot; پیدا نشد!.
        /// </summary>
        public static string Roles_RegistetedRoleNotFound {
            get {
                return ResourceManager.GetString("Roles_RegistetedRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چی؟ نقش &quot;سیستمی&quot;؟ میخوای حذفش کنی؟ بترس از این کارت بترس!.
        /// </summary>
        public static string Roles_SystemRole {
            get {
                return ResourceManager.GetString("Roles_SystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوب این چیه دادی من ذخیرش کنم؟ نمی تونم که؛ سخته جون تو!.
        /// </summary>
        public static string Settings_NotSupportedValueType {
            get {
                return ResourceManager.GetString("Settings_NotSupportedValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوب این چیه دادی من ذخیرش کنم؟ نمی تونم که؛ سخته جون تو!.
        /// </summary>
        public static string UserAttributes_NotSupportedValueType {
            get {
                return ResourceManager.GetString("UserAttributes_NotSupportedValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; واسه &quot;{1}&quot; تکراریه! عوضش می کنی؟.
        /// </summary>
        public static string Validation_DuplicateValue {
            get {
                return ResourceManager.GetString("Validation_DuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترکیب &quot;{0}&quot; به ترتیب برای &quot;{1}&quot; اشاره به یک رکورد تکراری می کنه! عوضشون می کنی؟.
        /// </summary>
        public static string Validation_DuplicateValues {
            get {
                return ResourceManager.GetString("Validation_DuplicateValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی &quot;{0}&quot; رو درست وارد کردی؟ (مثلا: fa-IR).
        /// </summary>
        public static string Validation_InvalidCultureCode {
            get {
                return ResourceManager.GetString("Validation_InvalidCultureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی &quot;{0}&quot; رو درست وارد کردی؟ (مثلا: 1392/1/1).
        /// </summary>
        public static string Validation_InvalidDateTime {
            get {
                return ResourceManager.GetString("Validation_InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی &quot;{0}&quot; رو درست وارد کردی؟ (با www شروع نمیشه، مثلا: me@gmail.com).
        /// </summary>
        public static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی &quot;{0}&quot; رو درست وارد کردی؟ (مثلا: 192.168.1.1).
        /// </summary>
        public static string Validation_InvalidIpAddress {
            get {
                return ResourceManager.GetString("Validation_InvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول &quot;{0}&quot; از {1} حرف بیشتر شده! کمش کن چه خبرته؟.
        /// </summary>
        public static string Validation_InvalidMaxLength {
            get {
                return ResourceManager.GetString("Validation_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; از {1} بیشتر شده! کمش کن چه خبرته؟.
        /// </summary>
        public static string Validation_InvalidMaxValue {
            get {
                return ResourceManager.GetString("Validation_InvalidMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول &quot;{0}&quot; کمتر از {1} حرف شده! خصیص بازی در آوردی؟.
        /// </summary>
        public static string Validation_InvalidMinLength {
            get {
                return ResourceManager.GetString("Validation_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; کمتر از {1}ست! جون تو کمتر راه نداره!.
        /// </summary>
        public static string Validation_InvalidMinValue {
            get {
                return ResourceManager.GetString("Validation_InvalidMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توی درخواستتون مقادیر غیر معتبر پیدا شده بود؛ ما در نظر نگرفتیم نگران نباشید..
        /// </summary>
        public static string Validation_InvalidParameter {
            get {
                return ResourceManager.GetString("Validation_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول &quot;{0}&quot; باید بین {1} و {2} حرف باشه! همینطوره؟.
        /// </summary>
        public static string Validation_InvalidRangeLength {
            get {
                return ResourceManager.GetString("Validation_InvalidRangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; باید بین {1} و {2} باشه! همینطوره؟.
        /// </summary>
        public static string Validation_InvalidRangeValue {
            get {
                return ResourceManager.GetString("Validation_InvalidRangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی &quot;{0}&quot; رو درست وارد کردی؟ (فقط میتونه شامل کاراکترهای A تا Z، اعداد و - باشه! مثلا: my-first-entry).
        /// </summary>
        public static string Validation_InvalidSlug {
            get {
                return ResourceManager.GetString("Validation_InvalidSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی &quot;{0}&quot; رو درست وارد کردی؟ (مثلا: Iran Standard Time).
        /// </summary>
        public static string Validation_InvalidTimeZoneId {
            get {
                return ResourceManager.GetString("Validation_InvalidTimeZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی &quot;{0}&quot; رو درست وارد کردی؟ (مثلا: http://webplex.ir/).
        /// </summary>
        public static string Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; و &quot;{1}&quot; با هم یکی نیستن!.
        /// </summary>
        public static string Validation_NotMatched {
            get {
                return ResourceManager.GetString("Validation_NotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای &quot;{0}&quot; یه مقدار عددی و مثبت وارد کن!.
        /// </summary>
        public static string Validation_PositiveNumericRequired {
            get {
                return ResourceManager.GetString("Validation_PositiveNumericRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این رو وارد نکردی!.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
