//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPlex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPlex.Resources.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت به خانه.
        /// </summary>
        public static string Commands_BackToHome {
            get {
                return ResourceManager.GetString("Commands_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر بده!.
        /// </summary>
        public static string Commands_ChangePassword {
            get {
                return ResourceManager.GetString("Commands_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال کن!.
        /// </summary>
        public static string Commands_ResetPassword {
            get {
                return ResourceManager.GetString("Commands_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اسم شب.
        /// </summary>
        public static string Commands_SetPassword {
            get {
                return ResourceManager.GetString("Commands_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Commands_SignIn {
            get {
                return ResourceManager.GetString("Commands_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Commands_SignUp {
            get {
                return ResourceManager.GetString("Commands_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیسبوک.
        /// </summary>
        public static string Literal_OAuth_Facebook {
            get {
                return ResourceManager.GetString("Literal_OAuth_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوگل.
        /// </summary>
        public static string Literal_OAuth_Google {
            get {
                return ResourceManager.GetString("Literal_OAuth_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینکد-این.
        /// </summary>
        public static string Literal_OAuth_LinkedIn {
            get {
                return ResourceManager.GetString("Literal_OAuth_LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مایکروسافت لایو.
        /// </summary>
        public static string Literal_OAuth_Microsoft {
            get {
                return ResourceManager.GetString("Literal_OAuth_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توئیتر.
        /// </summary>
        public static string Literal_OAuth_Twitter {
            get {
                return ResourceManager.GetString("Literal_OAuth_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یاهو!.
        /// </summary>
        public static string Literal_OAuth_Yahoo {
            get {
                return ResourceManager.GetString("Literal_OAuth_Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب‌پلکس.
        /// </summary>
        public static string Literal_Product {
            get {
                return ResourceManager.GetString("Literal_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یا.
        /// </summary>
        public static string Literal_SignIn_Or {
            get {
                return ResourceManager.GetString("Literal_SignIn_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری.
        /// </summary>
        public static string Literal_UserAccount {
            get {
                return ResourceManager.GetString("Literal_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه:.
        /// </summary>
        public static string Literal_Version {
            get {
                return ResourceManager.GetString("Literal_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب سایت شخصی محمدصادق شاد.
        /// </summary>
        public static string Subtitle_Home {
            get {
                return ResourceManager.GetString("Subtitle_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string Subtitle_SignIn {
            get {
                return ResourceManager.GetString("Subtitle_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره‌ی من.
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دست نوشته‌ها.
        /// </summary>
        public static string Title_Blog {
            get {
                return ResourceManager.GetString("Title_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر اسم شب.
        /// </summary>
        public static string Title_ChangePassword {
            get {
                return ResourceManager.GetString("Title_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با من.
        /// </summary>
        public static string Title_Contact {
            get {
                return ResourceManager.GetString("Title_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string Title_Dashboard {
            get {
                return ResourceManager.GetString("Title_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اسم شب.
        /// </summary>
        public static string Title_ResetPassword {
            get {
                return ResourceManager.GetString("Title_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب‌پلکس.
        /// </summary>
        public static string Title_Root {
            get {
                return ResourceManager.GetString("Title_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین اسم شب.
        /// </summary>
        public static string Title_SetPassword {
            get {
                return ResourceManager.GetString("Title_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Title_SignIn {
            get {
                return ResourceManager.GetString("Title_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Title_SignOut {
            get {
                return ResourceManager.GetString("Title_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Title_SignUp {
            get {
                return ResourceManager.GetString("Title_SignUp", resourceCulture);
            }
        }
    }
}
